# -*- coding: utf-8 -*-
"""formatted_zone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fMioIle0K2RgsVcD2p35EMhchxRyRlUt

# Formatted zone
"""

import pandas as pd
import os
from pathlib import Path

PERSISTENT_DIR = "landing/persistent/laciudadaldia/"
FORMATTED_DIR = "formatted/laciudadaldia/"
DATASET_NAME = "laciudadaldia"

persistent_paths = [
    Path(PERSISTENT_DIR + file_name)
    for file_name in os.listdir(PERSISTENT_DIR)
]

latest_file = sorted(persistent_paths)[-1]

print(f"Reading latest file '{latest_file}'")
persistent_data = pd.read_csv(latest_file)

ECONOMIC_INDICATORS_RENAMING = {
    "Carburants: Gasolina 95 i diesel A": "fuel_price",
    "Carn": "meat_price",
    "Carn i peix": "meat_and_fish_price",
    "Preu electricitat (majorista)": "electricity_price",
    "Compres amb targetes bancàries (% variació sobre el mateix periode de l'any anterior)": "credit_card_usage",
    "Indicador de reserves hoteleres domèstiques (base = mitjana suavitzada gener/febrer 2020)": "hotel_bookings_domestic",
    "Indicador de reserves hoteleres internacionals (base = mitjana suavitzada gener/febrer 2020)": "hotel_bookings_international",
    "Mercat bursàtil: IBEX-35": "ibex_35",
    "Peix i marisc": "fish_and_seafood_price",
}
ECONOMIC_INDICATORS = set(ECONOMIC_INDICATORS_RENAMING.keys())

formatted_data = (persistent_data
    .rename(columns=lambda col: col.lower())
    [["data_indicador", "nom_indicador", "nom_variable", "valor"]]
    .query("nom_indicador in @ECONOMIC_INDICATORS")
    .assign(nom_indicador=lambda df_: df_.nom_indicador
            .replace(ECONOMIC_INDICATORS_RENAMING))
    .astype({
        "data_indicador": "category",
        "valor": "float64"
        })
    .pivot_table(values="valor", index="data_indicador",
                 columns="nom_indicador", aggfunc="sum")
    .reset_index()
)

formatted_data

formatted_data.to_parquet(f"{FORMATTED_DIR}/{latest_file.stem}.parquet")