# -*- coding: utf-8 -*-
"""regression_model_training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17kHvkG3iSjvXANGQSk_5ahHDKo5VOiKp

# Regression model training
"""

import pandas as pd
import numpy as np
import os

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from joblib import dump

ROOT_PATH = "./"
TRAIN_TEST_SPLIT = "model-training/train-test-split/"
TRAINED_MODEL = "model-training/trained-model/"

"""We have opted to use a linear regression model in order to simplify our approach and enhance the interpretability of the results and report."""

X_train = pd.read_parquet(
    ROOT_PATH
    + TRAIN_TEST_SPLIT
    + "X_train.parquet"
)

Y_train = pd.read_parquet(
    ROOT_PATH
    + TRAIN_TEST_SPLIT
    + "Y_train.parquet"
)

model = LinearRegression()
model.fit(X_train, Y_train['GoldsteinScale'])

dump(model, os.path.join(ROOT_PATH, TRAINED_MODEL, 'model.joblib'))