# -*- coding: utf-8 -*-
"""pca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17TxKtoRkgEN7p_ZKxGEiaRfQJUGA3UY-
"""

import pandas as pd
import numpy as np

ROOT_PATH = "./"
ANALYTICAL_PATH = "analytical-sandbox/daily_metrics.parquet"
FEATURE_GENERATION_PATH = "feature-generation/data-preparation/pca.parquet"

daily_metrics = (
    pd.read_parquet(
        ROOT_PATH
        + ANALYTICAL_PATH
    )
    .set_index("date")
    .replace(0, np.nan)
    .ffill()
    .bfill()
)
daily_metrics

daily_metrics.to_parquet(
    ROOT_PATH
    + FEATURE_GENERATION_PATH
)