# -*- coding: utf-8 -*-
"""regression_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hIvfWollPMNoWBVAo8w7Hf4XdEofE1Hz
"""

import pandas as pd
import numpy as np

ROOT_PATH = "./"
ANALYTICAL_PATH = "analytical-sandbox/articles_with_metrics.parquet"
FEATURE_GENERATION_PATH = "feature-generation/data-preparation/regression_model.parquet"

df = pd.read_parquet(
    ROOT_PATH
    + ANALYTICAL_PATH
)

# print("Samples:", df.index.size)
# print("Atributtes:", df.columns)

"""We have eliminated all missing values from our dataset as the regression model does not accommodate NaNs. This reduction in the number of samples is acceptable to us, given the sample size of our existing dataset."""

num_samples_before = len(df)

df_dropped = df.dropna()

num_samples_after = len(df_dropped)

num_samples_removed = num_samples_before - num_samples_after

# print("Num of deleted samples:", num_samples_removed)
# print("Number of remaining samples:", len(df))

df_dropped.to_parquet(
    ROOT_PATH
    + FEATURE_GENERATION_PATH
)