# -*- coding: utf-8 -*-
"""landing_zone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-yK6ZSJIXykHouP39GZ1jXclfXzmYkvW
"""

import pandas as pd
import datetime
import shutil
import os

LANDING_PATH = "C:/Users/inigo/Documents/UPC/ASDB/ASDB/landing/"
TEMPORAL_PATH = "temporal/"
PERSISTENT_PATH = "persistent/articles/"
PERSISTENT_FILE_NAME = "articles"
LANDING_ZONE_FILE = "articles.CSV"

source_path = LANDING_PATH + TEMPORAL_PATH + LANDING_ZONE_FILE

ingestion_time = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
destination_path = (LANDING_PATH +
                    PERSISTENT_PATH +
                    PERSISTENT_FILE_NAME +
                    ingestion_time +
                    ".csv")

print(f"Copying temporary file '{source_path}' to persistent file '{destination_path}'...")
shutil.copy(source_path, destination_path)