# -*- coding: utf-8 -*-
"""articles_with_prices

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kTNLGPrYgo5O6CIX6Pmfeb5o5GdF4aII

# Analytical Sandbox
"""

import pandas as pd

ROOT_PATH = "./"
EXPLOITATION_PATH = "exploitation/"
CONCEPT_1= "concept1.parquet"
ANALYTICAL_PATH = "analytical-sandbox/articles_with_metrics.parquet"


df = pd.read_parquet(
    ROOT_PATH
    + EXPLOITATION_PATH
    + CONCEPT_1)

"""As we need all of the data from the first concept to feed our linear model, we dont need to do some data transformations in this section."""

df.to_parquet(
    ROOT_PATH
    + ANALYTICAL_PATH
)

df