# -*- coding: utf-8 -*-
"""daily_metrics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FznF1LHGHhdRE7NbQarR_Uom-cktqUjs

# Analytical Sandbox
"""

import pandas as pd

ROOT_PATH = "./"
EXPLOITATION_PATH = "exploitation/"
CONCEPT_2= "concept2.parquet"
ANALYTICAL_PATH = "analytical-sandbox/daily_metrics.parquet"

daily_metrics = (
    pd.read_parquet(
        ROOT_PATH
        + EXPLOITATION_PATH
        + CONCEPT_2
    )
    .rename(columns={
        "SQLDATE": "date",
        "GoldsteinScale": "goldstein_scale",
        "AvgTone": "avg_tone",
        "NumMentions": "num_mentions",
        "NumSources": "num_sources",
        "NumArticles": "num_articles"
    })
)
daily_metrics

daily_metrics.to_parquet(
    ROOT_PATH
    + ANALYTICAL_PATH
)