# -*- coding: utf-8 -*-
"""regression_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JF9mwaindwNeQszXvSQrheJz8cw1qt52
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

ROOT_PATH = "./"
FEATURE_GENERATION_PATH = "feature-generation/data-preparation/regression_model.parquet"
LABELLING = "feature-generation/labelling/regression_model.parquet"

df = pd.read_parquet(
    ROOT_PATH
    + FEATURE_GENERATION_PATH
)

"""Since it is a linear regression model, we have employed label encoding to transform the variables, as the previous format was not valid for this application."""

variable_types = {}
for column in df.columns:
    if pd.api.types.is_numeric_dtype(df[column]):
        variable_types[column] = {'type': 'numeric'}
    else:
        variable_types[column] = {
            'type': 'categorical',
            'num_categories': df[column].nunique()
        }

variable_types

categorical_vars = [
    'SQLDATE', 'Actor1Code', 'Actor1Name', 'Actor1CountryCode',
    'Actor1Type1Code', 'Actor2Code', 'Actor2Name', 'Actor2CountryCode',
    'Actor2Type1Code', 'Actor1Geo_FullName', 'Actor1Geo_CountryCode',
    'Actor1Geo_ADM1Code', 'Actor1Geo_FeatureID', 'Actor2Geo_FullName',
    'Actor2Geo_CountryCode', 'Actor2Geo_ADM1Code', 'Actor2Geo_FeatureID',
    'ActionGeo_FullName', 'ActionGeo_CountryCode', 'ActionGeo_ADM1Code',
    'ActionGeo_FeatureID'
]

for var in categorical_vars:
    label_encoder = LabelEncoder()
    df[var] = label_encoder.fit_transform(df[var].astype(str))

df.to_parquet(
    ROOT_PATH
    + LABELLING
)

df